[project]
name = "helix"
queries = "./db/"
container_runtime = "docker"

[local.dev]
port = 6969
build_mode = "debug"

[cloud.Marble.helix]
cluster_id = "1f0d4e37-db2f-6315-874a-010203040506"
region = "us-east-1"
build_mode = "dev"

[cloud.Marble.helix.env_vars]
